### ISSUE TITLE
A problem when import torch

### ISSUE THREAD

**Issue by YanGGGL** [ffhibnese/CPGC_VLP_Universal_Attacks#2]
I used "conda env create -f environment.yml" to set the environment and run train.py. Then I got a problem as follow:

    from torch._C import *  # noqa: F403
ImportError: /root/miniconda3/envs/CPGC/lib/python3.8/site-packages/torch/lib/libtorch_cuda.so: undefined symbol: ncclCommRegister

If I don't use the virtual environment, there is nothing wrong when I import torch. So maybe the problem is in environment.yml.
I hope you can help me on this problem.

**Comment by ffhibnese** [comment]
Hello Yan,
This might be the incompatibility between the torch version and the CUDA version installed in your GPU server.
You can either change the torch version or upgrade the CUDA version to solve this issue.

**Comment by YanGGGL** [comment]
Thank you for you reply. 
The torch version and the CUDA version is compatible actually. I loosed the version of python packages and it finally worked.
But I got other problems. Why the in_channels of the residual layer is set to batch_size which equals to 20. And when I run train.py with 4 GPUs, I met the following error : RuntimeError: Given groups=1, weight of size [1, 20, 3, 3], expected input[1, 5, 16, 48] to have 20 channels, but got 5 channels instead.
Intuitively, it seems like I should set the in_channels of the residual layer to 5. But that is kind of weird for me. I hope you can help me out.

**Comment by KongJiawei1231** [comment]
> Thank you for you reply. The torch version and the CUDA version is compatible actually. I loosed the version of python packages and it finally worked. But I got other problems. Why the in_channels of the residual layer is set to batch_size which equals to 20. And when I run train.py with 4 GPUs, I met the following error : RuntimeError: Given groups=1, weight of size [1, 20, 3, 3], expected input[1, 5, 16, 48] to have 20 channels, but got 5 channels instead. Intuitively, it seems like I should set the in_channels of the residual layer to 5. But that is kind of weird for me. I hope you can help me out.

Multi-GPU training is not implemented in our code. Please specify only one GPU when running train.py.
